name: tns_voting_service_app
description: "Приложение для Голосования совета директоров ТНС"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2
dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  url_launcher: ^6.1.11
  open_file: ^3.5.10
  permission_handler: ^11.4.0
  device_info_plus: ^9.1.2
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets: 
    - assets/logoTNS.png
    - assets/logoTNS2.png
    - assets/gosusl.png
    - assets/App_logo.png
